# -*- coding: utf-8 -*-
"""Directories

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cH5_Qxcy0Cb1fjDQt5v-m7IqrmkBdMBj
"""

import os
import zipfile

directories = [
'terraform-aws-vpc-infrastructure',
'terraform-aws-vpc-infrastructure/modules',
'terraform-aws-vpc-infrastructure/modules/vpc',
'terraform-aws-vpc-infrastructure/modules/ec2'
]

for directory in directories:
os.makedirs(directory, exist_ok=True)
print("Directory structure created successfully!")